//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyThiCong.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DuAnHienTai {
            get {
                return ((string)(this["DuAnHienTai"]));
            }
            set {
                this["DuAnHienTai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CongTrinhHienTai {
            get {
                return ((string)(this["CongTrinhHienTai"]));
            }
            set {
                this["CongTrinhHienTai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathHienTai {
            get {
                return ((string)(this["PathHienTai"]));
            }
            set {
                this["PathHienTai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TokenTBT {
            get {
                return ((string)(this["TokenTBT"]));
            }
            set {
                this["TokenTBT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserId {
            get {
                return ((string)(this["UserId"]));
            }
            set {
                this["UserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempInfo {
            get {
                return ((string)(this["TempInfo"]));
            }
            set {
                this["TempInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YWq5h8MUB92Zt8x0ejhzlA==")]
        public string CategoryCode {
            get {
                return ((string)(this["CategoryCode"]));
            }
            set {
                this["CategoryCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KJA5d/2ULIuU0jqPt8s7HXhjm9Y7ynjkzoCVcOWH4AulBrHc4+keZn9yntNPpPbjTeWc0tfJmzvdgL+qY" +
            "V7eDQ==")]
        public string UriChat {
            get {
                return ((string)(this["UriChat"]));
            }
            set {
                this["UriChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KJA5d/2ULIuU0jqPt8s7HXhjm9Y7ynjkzoCVcOWH4AulBrHc4+keZn9yntNPpPbjbYisE+/bzWJxff/yk" +
            "1R85A==")]
        public string UriAPI {
            get {
                return ((string)(this["UriAPI"]));
            }
            set {
                this["UriAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KJA5d/2ULIuU0jqPt8s7HXhjm9Y7ynjkzoCVcOWH4AulBrHc4+keZn9yntNPpPbjTeWc0tfJmzvdgL+qY" +
            "V7eDQ==")]
        public string ThoiTietAPI {
            get {
                return ((string)(this["ThoiTietAPI"]));
            }
            set {
                this["ThoiTietAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MK+wX9R0y4ZXrzgM2Nj95rB1x9NVpXiXdd+GLeKuMLyXEIFc8iHN2t42XEWF4Ze9VpdwEGcdZAvmYNqew" +
            "S6QgNUwUj62d3LwHADs0tSri+s=")]
        public string KeyOldAPI {
            get {
                return ((string)(this["KeyOldAPI"]));
            }
            set {
                this["KeyOldAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCache {
            get {
                return ((bool)(this["UseCache"]));
            }
            set {
                this["UseCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempLengh_3 {
            get {
                return ((string)(this["TempLengh_3"]));
            }
            set {
                this["TempLengh_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempLengh_2 {
            get {
                return ((string)(this["TempLengh_2"]));
            }
            set {
                this["TempLengh_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempLengh_1 {
            get {
                return ((string)(this["TempLengh_1"]));
            }
            set {
                this["TempLengh_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempLengh_0 {
            get {
                return ((string)(this["TempLengh_0"]));
            }
            set {
                this["TempLengh_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempCountBlock {
            get {
                return ((string)(this["TempCountBlock"]));
            }
            set {
                this["TempCountBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TokenCustomer {
            get {
                return ((string)(this["TokenCustomer"]));
            }
            set {
                this["TokenCustomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempCategoryCode {
            get {
                return ((string)(this["TempCategoryCode"]));
            }
            set {
                this["TempCategoryCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsLicenseMode {
            get {
                return ((bool)(this["IsLicenseMode"]));
            }
            set {
                this["IsLicenseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SerialNo {
            get {
                return ((string)(this["SerialNo"]));
            }
            set {
                this["SerialNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllPermission {
            get {
                return ((string)(this["AllPermission"]));
            }
            set {
                this["AllPermission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Token {
            get {
                return ((string)(this["Token"]));
            }
            set {
                this["Token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Province {
            get {
                return ((string)(this["Province"]));
            }
            set {
                this["Province"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CongTacInNhomVisible {
            get {
                return ((bool)(this["CongTacInNhomVisible"]));
            }
            set {
                this["CongTacInNhomVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDivisionVolume {
            get {
                return ((bool)(this["AutoDivisionVolume"]));
            }
            set {
                this["AutoDivisionVolume"] = value;
            }
        }
    }
}
